### ISSUE TITLE
The project team can provide the latest version of chart 

### ISSUE THREAD

**Issue by fi-ecavc** [openimsdk/openim-charts#10]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Solution Description

The project team can provide the latest version of chart 

### Benefits

It can quickly experiment with new functions in the K8S environment and accelerate the pace of production.

**Comment by cubxxw** [comment]
https://github.com/OpenIMSDK/openim-charts

**Comment by cubxxw** [comment]
On the way

**Comment by fi-ecavc** [comment]
Nice！
